# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Create release
      env:
        TOKEN: ${{ secrets.GH_PAT }}
      shell: bash
      run: |
        git config user.email "rey.suela@assurity.co.nz"
        git config user.name "reysuela"
        export version=$(./gradlew properties | grep version | cut -d':' -f 2 | xargs)
        echo ${version//-SNAPSHOT/} > version
        cat version
